/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-05-11 21:56:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updatepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/deeks/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1741240764871L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>User Registration Portal</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary: #4361ee;\r\n");
      out.write("            --primary-dark: #3a56d4;\r\n");
      out.write("            --secondary: #3f37c9;\r\n");
      out.write("            --accent: #4895ef;\r\n");
      out.write("            --light: #f8f9fa;\r\n");
      out.write("            --dark: #212529;\r\n");
      out.write("            --gray: #6c757d;\r\n");
      out.write("            --success: #4cc9f0;\r\n");
      out.write("            --danger: #f72585;\r\n");
      out.write("            --warning: #f8961e;\r\n");
      out.write("            --info: #4895ef;\r\n");
      out.write("            --transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navigation */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            box-shadow: 0 2px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo i {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            color: var(--accent);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a:hover {\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -5px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            background: var(--primary);\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a:hover::after {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Container */\r\n");
      out.write("        .main-container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 2rem auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Form Container */\r\n");
      out.write("        .form-container {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 2.5rem;\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container:hover {\r\n");
      out.write("            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header h1 {\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header p {\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -15px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: var(--accent);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Form Elements */\r\n");
      out.write("        .form-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(2, 1fr);\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group.full-width {\r\n");
      out.write("            grid-column: span 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: var(--dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-wrapper {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-wrapper i {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 15px;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"email\"],\r\n");
      out.write("        input[type=\"tel\"],\r\n");
      out.write("        input[type=\"password\"],\r\n");
      out.write("        select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px 12px 40px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            background-color: rgba(245, 245, 245, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus,\r\n");
      out.write("        select:focus {\r\n");
      out.write("            border-color: var(--accent);\r\n");
      out.write("            outline: none;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(67, 97, 238, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .radio-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            margin-top: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .radio-option {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .radio-option input {\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("            accent-color: var(--primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .button-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 12px 30px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn i {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: var(--primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: var(--primary-dark);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(67, 97, 238, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background-color: var(--success);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background-color: #3ab5d9;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(76, 201, 240, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-warning {\r\n");
      out.write("            background-color: var(--warning);\r\n");
      out.write("            color: white;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-warning:hover {\r\n");
      out.write("            background-color: #e68a19;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(248, 150, 30, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* User Data Section */\r\n");
      out.write("        .data-section {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 2.5rem;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            padding-bottom: 1rem;\r\n");
      out.write("            border-bottom: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-header h2 {\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-cards {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);\r\n");
      out.write("            transition: var(--transition);\r\n");
      out.write("            border: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-color: var(--accent);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            padding-bottom: 1rem;\r\n");
      out.write("            border-bottom: 1px dashed #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-name {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: var(--primary);\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-gender {\r\n");
      out.write("            background: var(--accent);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 3px 10px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-details p {\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-details i {\r\n");
      out.write("            width: 25px;\r\n");
      out.write("            color: var(--gray);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-sm {\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-edit {\r\n");
      out.write("            background-color: var(--accent);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-edit:hover {\r\n");
      out.write("            background-color: #3d85d5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-delete {\r\n");
      out.write("            background-color: var(--danger);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-delete:hover {\r\n");
      out.write("            background-color: #e5177b;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .form-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group.full-width {\r\n");
      out.write("                grid-column: span 1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-links {\r\n");
      out.write("                margin-top: 1rem;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                justify-content: space-around;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .user-cards {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; transform: translateY(20px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fade-in {\r\n");
      out.write("            animation: fadeIn 0.5s ease-out forwards;\r\n");
      out.write("        }\r\n");
      out.write("        .user-table {\r\n");
      out.write("                    width: 100%;\r\n");
      out.write("                    border-collapse: collapse;\r\n");
      out.write("                    margin-top: 20px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .user-table th, .user-table td {\r\n");
      out.write("                    padding: 12px;\r\n");
      out.write("                    text-align: left;\r\n");
      out.write("                    border-bottom: 1px solid #ddd;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .user-table th {\r\n");
      out.write("                    background-color: var(--primary);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .user-table tr:nth-child(even) {\r\n");
      out.write("                    background-color: #f2f2f2;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .user-table tr:hover {\r\n");
      out.write("                    background-color: #e9e9e9;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .action-btn {\r\n");
      out.write("                    padding: 6px 12px;\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    border-radius: 4px;\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                    margin-right: 5px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .edit-btn {\r\n");
      out.write("                    background-color: var(--accent);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .delete-btn {\r\n");
      out.write("                    background-color: var(--danger);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                #result {\r\n");
      out.write("                    color: green;\r\n");
      out.write("                    margin: 10px 0;\r\n");
      out.write("                    font-weight: 500;\r\n");
      out.write("                }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     <!-- Navigation Bar -->\r\n");
      out.write("     <nav class=\"navbar\">\r\n");
      out.write("         <a href=\"#\" class=\"logo\">\r\n");
      out.write("             <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("             <span>UserPortal</span>\r\n");
      out.write("         </a>\r\n");
      out.write("         <div class=\"nav-links\">\r\n");
      out.write("             <a href=\"#\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("             <a href=\"viewUsers\"><i class=\"fas fa-users\"></i> Users</a>\r\n");
      out.write("             <a href=\"#\"><i class=\"fas fa-cog\"></i> Settings</a>\r\n");
      out.write("             <a href=\"#\"><i class=\"fas fa-question-circle\"></i> Help</a>\r\n");
      out.write("         </div>\r\n");
      out.write("     </nav>\r\n");
      out.write("\r\n");
      out.write("     <!-- Main Content -->\r\n");
      out.write("     <div class=\"main-container\">\r\n");
      out.write("         <!-- Registration Form -->\r\n");
      out.write("         <div class=\"form-container fade-in\">\r\n");
      out.write("             <div class=\"form-header\">\r\n");
      out.write("                 <h1>Update Form</h1>\r\n");
      out.write("                 <div id=\"result\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                 <p>Please fill in all the required fields</p>\r\n");
      out.write("             </div>\r\n");
      out.write("\r\n");
      out.write("             <form id=\"registrationFormupdate\" action=\"update\" method=\"post\">\r\n");
      out.write("            <div class=\"form-grid\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"name\">Full Name</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <i class=\"fas fa-user\"></i>\r\n");
      out.write("                            <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"John Doe\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\">Email Address</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                            <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"john@example.com\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"mobile\">Mobile Number</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                            <input type=\"tel\" id=\"mobile\" name=\"mobile\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"+91 84478 52890\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"city\">City</label>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <i class=\"fas fa-city\"></i>\r\n");
      out.write("                            <select id=\"city\" name=\"city\"  required>\r\n");
      out.write("                                <option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.city}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.city}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("                                <option value=\"Bangalore\">Bangalore</option>\r\n");
      out.write("                                <option value=\"Mysore\">Mysore</option>\r\n");
      out.write("                                <option value=\"Madikeri\">Madikeri</option>\r\n");
      out.write("                                <option value=\"Mangalore\">Mangalore</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group full-width\">\r\n");
      out.write("                        <label>Gender</label>\r\n");
      out.write("                        <div class=\"radio-group\">\r\n");
      out.write("                            <div class=\"radio-option\">\r\n");
      out.write("                                <input type=\"radio\" id=\"male\" name=\"gender\" value=\"male\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender == 'male' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                <label for=\"male\">Male</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"radio-option\">\r\n");
      out.write("                                <input type=\"radio\" id=\"female\" name=\"gender\" value=\"female\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender == 'female' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                <label for=\"female\">Female</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"radio-option\">\r\n");
      out.write("                                <input type=\"radio\" id=\"other\" name=\"gender\" value=\"other\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender == 'other' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                <label for=\"other\">Other</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"radio-option\">\r\n");
      out.write("                                <input type=\"radio\" id=\"prefer-not-to-say\" name=\"gender\" value=\"prefer not to say\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.gender == 'prefer not to say' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                <label for=\"prefer-not-to-say\">Prefer not to say</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"button-group\">\r\n");
      out.write("                     <button type=\"submit\" id=\"saveBtn\" class=\"btn btn-primary\">\r\n");
      out.write("                         <i class=\"fas fa-save\"></i> update\r\n");
      out.write("                     </button>\r\n");
      out.write("                 </div>\r\n");
      out.write("             </form>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
